/* Generated by Report Generator v3.7 (R2009b) */
var gHomeSys = "vrmaglev";
var gNumSys = 12;
var gFrameID = {
"frameset_main":"vrmaglev_slwebview_main_frameset",
"explorer":"vrmaglev_slwebview_explorer",
"frameset_model":"vrmaglev_slwebview_frame",
"model":"vrmaglev_slwebview_model",
"web":"vrmaglev_slwebview_web"};
var gIDMap = {
"vrmaglev":{"target":"slwebview_1.svg","thumb":"slwebview_1_tb.png"},
"vrmaglev/Coordinates Transformation":{"target":"slwebview_2.svg","thumb":"slwebview_2_tb.png"},
"vrmaglev/Discrete-Time PID":{"target":"slwebview_3.svg","thumb":"slwebview_3_tb.png"},
"vrmaglev/Magnetic Levitation Plant Model":{"target":"slwebview_4.svg","thumb":"slwebview_4_tb.png"},
"vrmaglev/Switch Setpoint Selection Method Virtual Reality // Generator":{"target":"slwebview_5.svg","thumb":"slwebview_5_tb.png"},
"vrmaglev/VR Sensor Reader":{"target":"slwebview_6.svg","thumb":"slwebview_6_tb.png"},
"vrmaglev/Discrete-Time PID/Discrete-Time Limited Integrator":{"target":"slwebview_7.svg","thumb":"slwebview_7_tb.png"},
"vrmaglev/Magnetic Levitation Plant Model/AD converter and Position sensor":{"target":"slwebview_8.svg","thumb":"slwebview_8_tb.png"},
"vrmaglev/Magnetic Levitation Plant Model/D//A Converter":{"target":"slwebview_9.svg","thumb":"slwebview_9_tb.png"},
"vrmaglev/Magnetic Levitation Plant Model/Limits":{"target":"slwebview_10.svg","thumb":"slwebview_10_tb.png"},
"vrlib/VR Placeholder":{"target":"slwebview_11.svg","thumb":"slwebview_11_tb.png"},
"vrlib/VR Signal Expander":{"target":"slwebview_12.svg","thumb":"slwebview_12_tb.png"}};

