/* Generated by Report Generator v3.7 (R2009b) */
var gHomeSys = "bbbb";
var gNumSys = 2;
var gFrameID = {
"frameset_main":"bbbb_slwebview_main_frameset",
"explorer":"bbbb_slwebview_explorer",
"frameset_model":"bbbb_slwebview_frame",
"model":"bbbb_slwebview_model",
"web":"bbbb_slwebview_web"};
var gIDMap = {
"bbbb":{"target":"slwebview_1.svg","thumb":"slwebview_1_tb.png"},
"bbbb/Thermal Plant  I//O Interface":{"target":"slwebview_2.svg","thumb":"slwebview_2_tb.png"}};

